classdef (Sealed) Capacitor < UI.InteractableDevice
    properties (Constant, Access = private) %todo manage
        ImagePath = "D:\\tiny-spice\\sprites\\capacitor.png";
    end

    properties (SetAccess = protected)
        Width  = 56;
        Height = 22;
    end

    methods (Access = public)
        function capacitor = Capacitor(ax, x, y)
            capacitor@UI.InteractableDevice(x, y, ax);
            capacitor.draw();
        end

        function draw(obj)
            [img, ~, alpha] = imread(obj.ImagePath);

            left   = obj.X - (obj.Width / 2);
            right  = obj.X + (obj.Width / 2);
            bottom = obj.Y - (obj.Height / 2);
            top    = obj.Y + (obj.Height / 2);

            obj.Sprite = image(obj.CanvasAxes, ...
                XData         = [left, right], ...
                YData         = [top, bottom], ...
                CData         = cat(3, ~img, ~img, ~img), ...
                AlphaData     = alpha, ...
                HitTest       = "on", ...
                ButtonDownFcn = @obj.onCapacitorClick ...
            );

            % todo debugPivots()

            radius = 3;
            circle1 = rectangle(obj.CanvasAxes, ...
                Position  = [obj.X - radius - obj.Width / 2, obj.Y - radius, radius*2, radius*2], ...
                Curvature = [1 1], ...
                FaceColor = "red", ...
                EdgeColor = "none", ...
                HitTest   = "off" ...
            );

            circle2 = rectangle(obj.CanvasAxes, ...
                Position  = [obj.X - radius + obj.Width / 2, obj.Y - radius, radius*2, radius*2], ...
                Curvature = [1 1], ...
                FaceColor = "red", ...
                EdgeColor = "none", ...
                HitTest   = "off" ...
            );
        end
    end

    methods (Access = private)
        function onCapacitorClick(obj, ~, ~)
        end
    end
end