classdef (Abstract) InteractableDevice < UI.TinySpiceUI
    properties (Access = public)
        X          double
        Y          double
        CanvasAxes matlab.ui.control.UIAxes

        Name
        EntryNode
        ExitNode
    end

    properties (Constant, Access = protected)
        FillColor = "#121212";
        StrokeColor = "white";
        StrokeWidth = 2;

        PivotColor = "red";
        PivotRadius = 3.5;
    end

    methods (Access = public)
        function device = InteractableDevice(x, y, axes)
            device.X = x;
            device.Y = y;
            device.CanvasAxes = axes;
        end

        function onClick(device, source, event)
            device.showPropertiesWindow();

            disp("CLICL");
        end
    end

    methods (Access = protected)
        function drawLine(device, x, y)
            line(device.CanvasAxes, ...
                XData     = x, ...
                YData     = y, ...
                Color     = device.StrokeColor, ...
                LineWidth = device.StrokeWidth, ...
                HitTest   = "on", ...
                ButtonDownFcn = @device.onClick ...
            );
        end

        function drawRectangle(device, x, y, width, height)
            rectangle(device.CanvasAxes, ...
                Position  = [x, y, width, height], ...
                EdgeColor = device.StrokeColor, ...
                FaceColor = device.FillColor, ...
                LineWidth = device.StrokeWidth, ...
                HitTest   = "on", ...
                ButtonDownFcn = @device.onClick ...
            );
        end

        function drawCircle(device, x, y, radius)
            rectangle(device.CanvasAxes, ...
                Position  = [x - radius, y - radius, radius*2, radius*2], ...
                Curvature = [1, 1], ...
                EdgeColor = device.StrokeColor, ...
                FaceColor = device.FillColor, ...
                LineWidth = device.StrokeWidth, ...
                HitTest   = "on", ...
                ButtonDownFcn = @device.onClick ...
            );
        end

        function drawPolygon(device, x, y)
            patch(device.CanvasAxes, ...
                XData     = x, ...
                YData     = y, ...
                EdgeColor = device.StrokeColor, ...
                FaceColor = device.FillColor, ...
                LineWidth = device.StrokeWidth, ...
                HitTest   = "on", ...
                ButtonDownFcn = @device.onClick ...
            );
        end

        function drawPivot(device, x, y)
            rectangle(device.CanvasAxes, ...
                Position = [...
                    x - device.PivotRadius, ...
                    y - device.PivotRadius, ...
                    device.PivotRadius * 2, ...
                    device.PivotRadius * 2, ...
                ], ...
                Curvature = [1 1], ...
                FaceColor = device.PivotColor, ...
                EdgeColor = "none", ...
                HitTest   = "off" ...
            );
        end

        function setProperty(device, name, value)
            device.(name) = value;
        end
    end

    methods (Access = private)
        function showPropertiesWindow(device)
            fig = uifigure(...
                'Name', class(device) + " Properties", ...
                'WindowStyle', 'modal', ...
                'Resize', 'off' ...
            );

        end
    end

    methods (Abstract, Access = public)
        [x, y] = getPivotPositions(device);
        draw(device);
    end
end
