classdef (Sealed) MenuBar < UI.TinySpiceUI
    properties (Access = public)
        FileMenu   matlab.ui.container.Menu
        EditMenu   matlab.ui.container.Menu
        ViewMenu   matlab.ui.container.Menu
        RunMenu    matlab.ui.container.Menu
        WindowMenu matlab.ui.container.Menu
        HelpMenu   matlab.ui.container.Menu
    end

    % todo refactor into ToolManager and dynamically load tools
    events
        FileNew, FileOpen, FileSave, FileSaveAs
        FileExit

        EditUndo, EditRedo
        EditCut, EditCopy, EditPaste, EditDelete

        EditPlaceResistor, EditPlaceCapacitor, EditPlaceInductor, EditPlaceGround,
        EditPlaceBreaker, EditPlaceVoltageSource, EditPlaceCurrentSource, EditPlaceWire

        % todo checkbox for View

        RunDC, RunAC
        RunCheck

        WindowRefresh

        HelpHelp, HelpAbout
    end

    methods (Access = public)
        function menuBar = MenuBar(window)
            arguments
                window matlab.ui.Figure
            end

            menuBar.renderFileMenu(window);
            menuBar.renderEditMenu(window);
            menuBar.renderViewMenu(window);
            menuBar.renderRunMenu(window);
            menuBar.renderWindowMenu(window);
            menuBar.renderHelpMenu(window);
        end
    end

    methods (Access = private)
        function renderFileMenu(menuBar, parent)
            arguments
                menuBar UI.MenuBar
                parent  matlab.ui.Figure
            end

            menuBar.FileMenu = uimenu(parent, Text = '&File');

            uimenu(menuBar.FileMenu, ...
                Text            = '&New', ...
                Accelerator     = 'N', ...
                MenuSelectedFcn = @(src, ev) notify(menuBar, 'FileNew') ...
            );

            uimenu(menuBar.FileMenu, ...
                Text            = '&Open', ...
                Accelerator     = 'O', ...
                MenuSelectedFcn = @(src, ev) notify(menuBar, 'FileOpen') ...
            );

            uimenu(menuBar.FileMenu, ...
                Text            = '&Save', ...
                Accelerator     = 'S', ...
                MenuSelectedFcn = @(src, ev) notify(menuBar, 'FileSave') ...
            );

            uimenu(menuBar.FileMenu, ...
                Text            = 'Save &As', ...
                MenuSelectedFcn = @(src, ev) notify(menuBar, 'FileSaveAs') ...
            );

            uimenu(menuBar.FileMenu, ...
                Text            = 'E&xit', ...
                Separator       = true, ...
                MenuSelectedFcn = @(src, ev) notify(menuBar, 'FileExit') ...
            );
        end

        function renderEditMenu(menuBar, parent)
            arguments
                menuBar UI.MenuBar
                parent  matlab.ui.Figure
            end

            menuBar.EditMenu = uimenu(parent, Text = '&Edit');

            uimenu(menuBar.EditMenu, ...
                Text            = '&Undo', ...
                Accelerator     = 'Z', ...
                MenuSelectedFcn = @(src, ev) notify(menuBar, 'EditUndo') ...
            );

            uimenu(menuBar.EditMenu, ...
                Text            = '&Redo', ...
                Accelerator     = 'Y', ...
                MenuSelectedFcn = @(src, ev) notify(menuBar, 'EditRedo') ...
            );

            uimenu(menuBar.EditMenu, ...
                Text            = 'Cut', ...
                Accelerator     = 'X', ...
                Separator       = true, ...
                MenuSelectedFcn = @(src, ev) notify(menuBar, 'EditCut') ...
            );

            uimenu(menuBar.EditMenu, ...
                Text            = 'Copy', ...
                Accelerator     = 'C', ...
                MenuSelectedFcn = @(src, ev) notify(menuBar, 'EditCopy') ...
            );

            uimenu(menuBar.EditMenu, ...
                Text            = 'Paste', ...
                Accelerator     = 'V', ...
                MenuSelectedFcn = @(src, ev) notify(menuBar, 'EditPaste') ...
            );

            uimenu(menuBar.EditMenu, ...
                Text            = 'Delete', ...
                MenuSelectedFcn = @(src, ev) notify(menuBar, 'EditDelete') ...
            );

            placeMenu = uimenu(menuBar.EditMenu, Text = 'Place', Separator = true);

            uimenu(placeMenu, ...
                Text            = 'Resistor', ...
                MenuSelectedFcn = @(src, ev) notify(menuBar, 'EditPlaceResistor') ...
            );

            uimenu(placeMenu, ...
                Text            = 'Capacitor', ...
                MenuSelectedFcn = @(src, ev) notify(menuBar, 'EditPlaceCapacitor') ...
            );

            uimenu(placeMenu, ...
                Text            = 'Inductor', ...
                MenuSelectedFcn = @(src, ev) notify(menuBar, 'EditPlaceInductor') ...
            );

            uimenu(placeMenu, ...
                Text            = 'Geound', ...
                MenuSelectedFcn = @(src, ev) notify(menuBar, 'EditPlaceGround') ...
            );

            uimenu(placeMenu, ...
                Text            = 'Breaker', ...
                MenuSelectedFcn = @(src, ev) notify(menuBar, 'EditPlaceBreaker') ...
            );

            uimenu(placeMenu, ...
                Text            = 'Voltage Source', ...
                Separator       = true, ...
                MenuSelectedFcn = @(src, ev) notify(menuBar, 'EditPlaceVoltageSource') ...
            );

            uimenu(placeMenu, ...
                Text            = 'Current Source', ...
                MenuSelectedFcn = @(src, ev) notify(menuBar, 'EditPlaceCurrentSource') ...
            );

            uimenu(placeMenu, ...
                Text            = 'Wire', ...
                Separator       = true, ...
                MenuSelectedFcn = @(src, ev) notify(menuBar, 'EditPlaceWire') ...
            );
        end

        function renderViewMenu(menuBar, parent)
            arguments
                menuBar UI.MenuBar
                parent  matlab.ui.Figure
            end

            menuBar.ViewMenu = uimenu(parent, Text = '&View');

            uimenu(menuBar.ViewMenu, Text = '&Grid',           Checked = true);
            uimenu(menuBar.ViewMenu, Text = '&European Icons', Checked = true);
        end

        function renderRunMenu(menuBar, parent)
            arguments
                menuBar UI.MenuBar
                parent  matlab.ui.Figure
            end

            menuBar.RunMenu = uimenu(parent, Text = '&Run');

            uimenu(menuBar.RunMenu, ...
                Text            = 'Run &DC', ...
                MenuSelectedFcn = @(src, ev) notify(menuBar, 'RunDC') ...
            );

            uimenu(menuBar.RunMenu, ...
                Text            = 'Run &AC', ...
                MenuSelectedFcn = @(src, ev) notify(menuBar, 'RunAC') ...
            );

            uimenu(menuBar.RunMenu, ...
                Text            = 'Check connections', ...
                Separator       = true, ...
                MenuSelectedFcn = @(src, ev) notify(menuBar, 'RunCheck') ...
            );
        end

        function renderWindowMenu(menuBar, parent)
            arguments
                menuBar UI.MenuBar
                parent  matlab.ui.Figure
            end

            menuBar.WindowMenu = uimenu(parent, Text = '&Window');

            uimenu(menuBar.WindowMenu, ...
                Text            = '&Refresh', ...
                MenuSelectedFcn = @(src, ev) notify(menuBar, 'WindowRefresh') ...
            );
        end

        function renderHelpMenu(menuBar, parent)
            arguments
                menuBar UI.MenuBar
                parent  matlab.ui.Figure
            end

            menuBar.HelpMenu = uimenu(parent, Text = '&Help');

            uimenu(menuBar.HelpMenu, ...
                Text            = '&Help', ...
                MenuSelectedFcn = @(src, ev) notify(menuBar, 'HelpHelp') ...
            );

            uimenu(menuBar.HelpMenu, ...
                Text = 'Check for &updates...', ...
                Enable = false ...
            );

            uimenu(menuBar.HelpMenu, ...
                Text            = '&About', ...
                MenuSelectedFcn = @(src, ev) notify(menuBar, 'HelpAbout') ...
            );
        end
    end
end
