classdef (Sealed) ToolType
    enumeration
        PlaceResistor,
        PlaceCapacitor,
        PlaceInductor,
        PlaceBreaker,
        PlaceVoltageSource,
        PlaceCurrentSource,
        PlaceNode,
        PlaceGround,
        FreeRoam
    end

    methods
        function str = getIcon(toolType)
            persistent toolMap;

            if isempty(toolMap)
                toolMap = dictionary(...
                    UI.ToolType.PlaceResistor,      "R", ...
                    UI.ToolType.PlaceCapacitor,     "C", ...
                    UI.ToolType.PlaceInductor,      "L", ...
                    UI.ToolType.PlaceGround,        "G", ...
                    UI.ToolType.PlaceBreaker,       "B", ...
                    UI.ToolType.PlaceVoltageSource, "U", ...
                    UI.ToolType.PlaceCurrentSource, "I", ...
                    UI.ToolType.PlaceNode,          "+", ...
                    UI.ToolType.FreeRoam,           " " ...
                );
            end

            str = toolMap(toolType);
        end

        function str = getTooltip(toolType)
            persistent toolMap;

            if isempty(toolMap)
                toolMap = dictionary(...
                    UI.ToolType.PlaceResistor,      "Resistor", ...
                    UI.ToolType.PlaceCapacitor,     "Capacitor", ...
                    UI.ToolType.PlaceInductor,      "Inductor", ...
                    UI.ToolType.PlaceBreaker,       "Breaker", ...
                    UI.ToolType.PlaceVoltageSource, "Voltage Source", ...
                    UI.ToolType.PlaceCurrentSource, "Current Source", ...
                    UI.ToolType.PlaceNode,          "Node", ...
                    UI.ToolType.PlaceGround,        "Ground Node", ...
                    UI.ToolType.FreeRoam,           "Free Roam" ...
                );
            end

            str = toolMap(toolType);
        end
    end
end
