classdef (Sealed) TinySpice < handle
    properties % todo strong typing
        MainWindow
        MenuBar
    end

    methods (Access = public)
        function app = TinySpice()
            app.MainWindow = figure(...
                'Name',        'tinySPICE', ...
                'Position',    [200, 200, 400, 300], ...
                'MenuBar',     'none', ...
                'ToolBar',     'none', ...
                'NumberTitle', 'off' ...
            );

            app.renderMenuBar();
        end
    end

    methods (Access = private)
        function renderMenuBar(app)
            arguments
                app (1, 1) TinySpice
            end

            renderFileMenu();
            renderEditMenu();
            renderViewMenu();
            renderRunMenu();
            renderWindowMenu();
            renderHelpMenu();

            function renderFileMenu()
                app.MenuBar.File = uimenu(app.MainWindow, ...
                    'Label', '&File' ...
                );

                uimenu(app.MenuBar.File, ...
                    'Label', '&New', ...
                    'Accelerator', 'N' ...
                );

                uimenu(app.MenuBar.File, ...
                    'Label', '&Open', ...
                    'Accelerator', 'O' ...
                );

                uimenu(app.MenuBar.File, ...
                    'Label', '&Save', ...
                    'Accelerator', 'S' ...
                );

                uimenu(app.MenuBar.File, ...
                    'Label', 'Save &As' ...
                );

                uimenu(app.MenuBar.File, ...
                    'Label', 'E&xit', ...
                    'Separator', 'on' ...
                );
            end

            function renderEditMenu()
                app.MenuBar.Edit = uimenu(app.MainWindow, ...
                    'Label', '&Edit' ...
                );
            end

            function renderViewMenu()
                app.MenuBar.View = uimenu(app.MainWindow, ...
                    'Label', '&View' ...
                );
            end

            function renderRunMenu()
                app.MenuBar.Run = uimenu(app.MainWindow, ...
                    'Label', '&Run' ...
                );
            end

            function renderWindowMenu()
                app.MenuBar.Window = uimenu(app.MainWindow, ...
                    'Label', '&Window' ...
                );
            end

            function renderHelpMenu()
                app.MenuBar.Help = uimenu(app.MainWindow, ...
                    'Label', '&Help' ...
                );
            end
        end
    end
end
