classdef (Sealed) PropertiesWindow < handle
    properties (Constant, Access = private)
        Width  = 260;
        Height = 160;
    end


    properties (Access = private)
        Window;
        Device;
        NameField;
        ValueField;
    end


    methods (Access = public)
        function props = PropertiesWindow(device)
            props.Device = device;
            props.createWindow();
            props.createFields();
            props.createButtons();
        end
    end


    methods (Access = private)
        function createWindow(props)
            props.Window = uifigure(                                 ...
                Name        = 'Properties',                          ...
                Position    = [400, 400, props.Width, props.Height], ...
                Resize      = false,                                 ...
                WindowStyle = 'modal'                                ...
            );
        end

        function createFields(props)
            labelWidth  = 40;
            fieldX      = 16 + labelWidth + 8;
            fieldWidth  = props.Width - fieldX - 16;

            uilabel(props.Window,                       ...
                Text     = 'Name',                      ...
                Position = [16, 106, labelWidth, 22]    ...
            );
            props.NameField = uieditfield(props.Window, 'text',     ...
                Value    = props.Device.Device.Name,                ...
                Position = [fieldX, 106, fieldWidth, 22]            ...
            );

            uilabel(props.Window,                       ...
                Text     = 'Value',                     ...
                Position = [16, 72, labelWidth, 22]     ...
            );
            props.ValueField = uieditfield(props.Window, 'numeric', ...
                Value    = props.Device.Device.Value,               ...
                Position = [fieldX, 72, fieldWidth, 22]             ...
            );
        end

        function createButtons(props)
            uibutton(props.Window,                              ...
                Text            = 'Cancel',                     ...
                Position        = [84, 24, 80, 28],             ...
                ButtonPushedFcn = @(~,~) delete(props.Window)   ...
            );
            uibutton(props.Window,                              ...
                Text            = 'OK',                         ...
                Position        = [172, 24, 80, 28],            ...
                ButtonPushedFcn = @(~,~) props.onConfirm()      ...
            );
        end

        function onConfirm(props)
            props.Device.Device.Name  = props.NameField.Value;
            props.Device.Device.Value = props.ValueField.Value;
            props.Device.updateLabels();
            delete(props.Window);
        end
    end
end